apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kisielewski-dev
  name: nginx-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - kisielewski.dev
      secretName: kisielewski-dev-cert
  rules:
  - host: kisielewski.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: kisielewski-dev
  name: nginx-service
  labels:
    run: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app:  nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kisielewski-dev
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: dockerhub
      containers:
      - name: nginx
        image: wiktorkisielewski/kisielewski-dev:0.4
        ports:
        - containerPort: 80
