apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kisielew-ski
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
#  ingressClassName: traefik
  tls:
    - hosts:
      - kisielew.ski
      secretName: kisielew-ski-cert
  rules:
  - host: kisielew.ski
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: kisielew-ski
  name: nginx-service
  labels:
    run: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app:  nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kisielew-ski
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: dockerhub
      containers:
      - name: nginx
        image: wiktorkisielewski/kisielew-ski:0.5
        ports:
        - containerPort: 80
